import * as monaco from "monaco-editor";
export function getSqlSuggestionsKeywords() {
  const keywords = [
    "SELECT",
    "FROM",
    "SELECT * FROM",
    "WHERE",
    "GROUP BY",
    "HAVING",
    "ORDER BY",
    "LIMIT",
    "OFFSET",
    "JOIN",
    "INNER JOIN",
    "LEFT JOIN",
    "RIGHT JOIN",
    "FULL JOIN",
    "CROSS JOIN",
    "UNION",
    "UNION ALL",
    "EXCEPT",
    "INTERSECT",
    "ON",
    "AND",
    "OR",
    "NULL",
    "IS",
    "AS",
    "BETWEEN",
    "IN",
    "LIKE",
    "TRUNCATE",
    "CREATE",
    "TABLE",
    "IF",
    "NOT",
    "EXISTS",
    "DROP",
    "ALTER",
    "ADD",
    "MODIFY",
    "DELETE",
    "UPDATE",
    "INSERT",
    "VALUES",
    "DEFAULT",
    "DESC",
    "ASC",
  ];
  const suggestions = keywords.map((keyword) => ({
    label: keyword,
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: keyword,
  }));
  return suggestions;
}
